name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:

env:
  WORK_FOLDER_PATH: ./work
  BUILD_FOLDER_PATH: ./build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORK_FOLDER_PATH }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ${{ env.BUILD_FOLDER_PATH }}
          

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd "${{ env.WORK_FOLDER_PATH }}"
          npm install

      - name: Run Node.js script
        run: |
          # 在这里运行您的 Node.js 脚本，例如：
          node "${{ env.WORK_FOLDER_PATH }}/worker.js"

      - name: 同步 repo
        run: |
          cd "${{ env.BUILD_FOLDER_PATH }}"
          bash -c 'if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "工作树无变更，跳过提交步骤..."
          else
            echo "提交文件中..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "GitHub Actions Bot"
            git log -3 --oneline
            echo "推送更新中..."
            git push
          fi'
